services:
  db:
    image: postgres:17-alpine
    container_name: zabbix_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      zabbix_net:
        ipv4_address: 172.20.0.11
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix_server
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "1050:10050"
    volumes:
      - ./logs:/var/log/zabbix
      - ./zbx_env:/var/lib/zabbix
    networks:
      zabbix_net:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix_web
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      zabbix_net:
        ipv4_address: 172.20.0.12
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.3.0-security-01
    container_name: grafana
    restart: unless-stopped
    ports:
      - '8484:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      zabbix_net:
        ipv4_address: 172.20.0.13


networks:
  zabbix_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  grafana-storage:
