services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC      
    volumes:
      - /home/docker/emulatorjs/config:/config
      - /home/docker/emulatorjs/data:/data
    ports:
      - 3000:3000
      - 8585:80
      - 4001:4001 #optional
    restart: unless-stopped
